title: "My CTF Writeups"
description: "Solutions, scripts, and notes from cybersecurity competitions."
remote_theme: just-the-docs/just-the-docs
color_scheme: dark
search_enabled: true
markdown: kramdown
kramdown:
  input: GFM
